runners:
  - name: gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    region: eu-west-1
    machine_image: ami-05b60ba3674d8f819
    workflow: .github/workflows/MLops.yml
    labels:
      - gpu