runners:
  - name: gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    region: eu-west-1
    machine_image: ami-0bddab4f878f34289
    workflow: .github/workflows/MLops.yml
    labels:
      - gpu