name: MLops
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cirun.gpu]
    steps:
      - uses: actions/checkout@v2
      - name: MLops
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo Model metrics
          cat metrics.txt
          