name: MLops
on: 
  push:
    branches: [ "new-example-2" ]
  workflow_dispatch: 
jobs:
  run:
    runs-on: [self-hosted, cirun.gpu]
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        run:  sudo apt install nodejs -y
      - name: setup npm
        run:  sudo apt install npm -y
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Get Free Memory
        run: free -h
      - name: Run NVIDIA-SMI
        run: |
          echo Running nvidia-smi
          nvidia-smi
      - name: Dependency Install
        run: pip install -r requirements.txt
      - name: MLops
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          # Your ML workflow goes here
          python finalModel.py