name: GitHub Actions with your own GPUs
on: 
  push:
    branches: [ "none" ] #  When a push occurs on a branch workflow will trigger on your desired branch.
  workflow_dispatch: 
jobs:
  CPU_GPU_matrix: # Creating matrix for jobs.
    strategy:
      matrix:
        # Creating a 2d matrix to execute our jobs with respective docker containers.
        os: [ubuntu-latest, cirun.gpu] 
        containers: ["docker://dvcorg/cml-py3:latest" , "ghcr.io/iterative/cml:0-dvc2-base1-gpu" ]
        container_arg: [" " , "--gpus all"]
        # Excluding the unwanted docker container and container_arg in our respective OS.
        exclude:
          - os: ubuntu-latest
            containers: "ghcr.io/iterative/cml:0-dvc2-base1-gpu"
          - os: ubuntu-latest
            container_arg: "--gpus all"
          - os: self-hosted
            containers: docker://dvcorg/cml-py3:latest
          - os: self-hosted
            container_arg: " "
    # Workflow to run commands in OS.
    # Dynamic passing of os, containers, container_agr using matrix 
    runs-on: ${{ matrix.os }} 
    container:
      image: ${{ matrix.containers }}
      options: ${{ matrix.container_arg }}
    # Steps that we want to have with OS.
    steps:
      - uses: actions/checkout@v3
      - name: Get Free Memory
        run: free -h
      - name: Dependency Install
        run: pip install -r requirements.txt
      - name: MLops
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          python train.py