name: MLops
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: MLops
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          python --version 

          pip install -r requirements.txt
          python train.py
          
          echo Model metrics
          cat metrics.txt 