name: MLops
on: 
  push:
    branches: [ "GPU_test" ]
  workflow_dispatch: 
jobs:
  run:
    runs-on: self-hosted
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run NVIDIA-SMI
        run: |
          echo Running nvidia-smi
          nvidia-smi
      
      - name: MLops
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo Model metrics
          cat metrics.txt
     
          