name: MLops
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
         python-version: '3.10'
      - name: MLops
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade pip
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          